# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LandR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=88),
            preserve_default=False,
        ),
    ]
